"""empty message

Revision ID: 07d2dd364b65
Revises: 69bf7638e7df
Create Date: 2023-04-17 15:29:23.927379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d2dd364b65'
down_revision = '69bf7638e7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TokenBlocklist',
    sa.Column('block_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('block_id'),
    sa.UniqueConstraint('block_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('PaymentToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('Product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=30), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('favorite', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('UserToken',
    sa.Column('refresh_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('refresh_id'),
    sa.UniqueConstraint('refresh_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('ProductImage',
    sa.Column('img_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Product.product_id'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductImage')
    op.drop_table('UserToken')
    op.drop_table('Product')
    op.drop_table('PaymentToken')
    op.drop_table('User')
    op.drop_table('TokenBlocklist')
    # ### end Alembic commands ###
