"""empty message

Revision ID: 69bf7638e7df
Revises: ad98a967b025
Create Date: 2023-03-25 17:29:40.376128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69bf7638e7df'
down_revision = 'ad98a967b025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('Product_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['author_id'], ['user_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Product_ibfk_1', 'User', ['user_id'], ['user_id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
