CREATE DATABASE USAN;

CREATE TABLE `UserTB` (
	`id`	INT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`email`	VARCHAR(30)	NOT NULL,
	`nickname`	VARCHAR(10)	NOT NULL,
	`password`	VARCHAR(256)	NOT NULL,
	`address`	VARCHAR(40)	NULL,
	`created_date`	DATETIME	NOT NULL,
	`modified_date`	DATETIME	NOT NULL DEFAULT NOW()
);

CREATE TABLE `ProductTB` (
	`id`	INT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`title`	VARCHAR(50)	NOT NULL,
	`content`	VARCHAR(1000)	NOT NULL,
	`price`	INT UNSIGNED	NOT NULL,
	`address`	VARCHAR(40)	NOT NULL,
	`created_date`	DATETIME	NOT NULL,
	`modified_date`	DATETIME	NOT NULL DEFAULT NOW(),
	`status`	BOOLEAN	NOT NULL,
	`user_id`	INT UNSIGNED	NOT NULL
);

CREATE TABLE `ProductpictureTB` (
	`id`	INT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`url`	VARCHAR(50)	NULL,
	`product_id`	INT UNSIGNED	NOT NULL
);

ALTER table ProductTB add FOREIGN KEY(user_id) REFERENCES UserTB(id);
ALTER table ProductpictureTB add FOREIGN KEY(product_id) REFERENCES ProductTB(id);