CREATE TABLE `UserTB` (
	`id`	INT UNSIGNED	NOT NULL AUTO_INCREMENT,
	`email`	VARCHAR(30)	NOT NULL,
	`nickname`	VARCHAR(10)	NOT NULL,
	`password`	VARCHAR(256)	NOT NULL,
	`address`	VARCHAR(40)	NULL,
	`created_date`	DATETIME	NOT NULL,
	`modified_date`	DATETIME	NOT NULL	DEFAULT NOW()
);

CREATE TABLE `ProductTB` (
	`id`	INT UNSIGNED	NOT NULL AUTO_INCREMENT,
	`title`	VARCHAR(50)	NOT NULL,
	`content`	VARCHAR(1000)	NOT NULL,
	`price`	INT UNSIGNED	NOT NULL,
	`address`	VARCHAR(40)	NOT NULL,
	`created_date`	DATETIME	NOT NULL,
	`modified_date`	DATETIME	NOT NULL	DEFAULT NOW(),
	`status`	BOOL	NOT NULL,
	`user_id`	INT UNSIGNED	NOT NULL
);

CREATE TABLE `Product.pictureTB` (
	`id`	INT UNSIGNED	NOT NULL AUTO_INCREMENT,
	`url`	VARCHAR(50)	NULL,
	`product_id`	INT UNSIGNED	NOT NULL
);

ALTER TABLE `UserTB` ADD CONSTRAINT `PK_USERTB` PRIMARY KEY (
	`id`
);

ALTER TABLE `ProductTB` ADD CONSTRAINT `PK_PRODUCTTB` PRIMARY KEY (
	`id`
);

ALTER TABLE `Product.pictureTB` ADD CONSTRAINT `PK_PRODUCT.PICTURETB` PRIMARY KEY (
	`id`
);

